
name: Create golang vendor dist
on:
  push:
    tags:
      - '**'

jobs:
  golang-dist:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create golang dist
        uses: projg2/golang-dist-action@v1
        with:
          dist-filename: Xray-core-26.2.6
          vendor-dir: Xray-core-26.2.6

