name: Sync with upstream
on:
  schedule:
    - cron: "12 * * * *"
  push:

jobs:
  sync-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Update mirror
        uses: projg2/golang-dist-mirror-action@v1
        with:
          upstream-repo: https://github.com/XTLS/Xray-core.git
